services:
  - type: web
    name: marnagement
    env: node
    plan: starter
    autoDeploy: true
    buildCommand: npm ci --legacy-peer-deps && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
